services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=identity-db
      - POSTGRES_USER=identity-service
      - POSTGRES_PASSWORD=identity-service
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data: